import { useState, useEffect } from "react";
import { Layout } from "../../../Components/Sidebar";
import {
    Filter,
    FileText,
    Printer,
    Download,
    X,
    CheckCircle2,
} from "lucide-react";

const REPORT_TYPES = [
    "Evacuee Summary per Barangay",
    "Relief Distribution Report",
    "Shelter Occupancy Report",
    "Vulnerable Groups Summary",
    "Daily Operations Report",
];

function Toast({ message, onClose }) {
    useEffect(() => {
        const timer = setTimeout(onClose, 3000);
        return () => clearTimeout(timer);
    }, [onClose]);

    return (
        <div className="fixed top-6 right-6 z-50 animate-in fade-in slide-in-from-top-5 duration-300">
            <div className="bg-white dark:bg-gray-800 border border-gray-100 dark:border-gray-700 shadow-xl rounded-xl p-4 flex items-center gap-3">
                <CheckCircle2 className="text-teal-500" size={20} />
                <p className="text-sm font-medium text-gray-800 dark:text-gray-100">
                    {message}
                </p>
                <button
                    onClick={onClose}
                    className="ml-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                >
                    <X size={16} />
                </button>
            </div>
        </div>
    );
}

export default function GenerateReport() {
    const [reportType, setReportType] = useState(
        "Evacuee Summary per Barangay",
    );
    const [dateFrom, setDateFrom] = useState("");
    const [dateTo, setDateTo] = useState("");
    const [format, setFormat] = useState("pdf");

    const [generated, setGenerated] = useState(false);
    const [toastMessage, setToastMessage] = useState(null);

    const handleGenerate = () => {
        setGenerated(true);
        setToastMessage(`"${reportType}" generated successfully.`);
    };

    const handleDownload = () => {
        let content = "";
        let filename = "";
        let mimeType = "";

        if (format === "excel") {
            content =
                "Barangay,Families\nBarangay Mamatid,14\nBarangay Sala,11\nBarangay Marinig,8\nBarangay Gulod,9\nBarangay Banay-Banay,18\nTotal,60";
            filename = `${reportType.replace(/\s+/g, "_")}.csv`;
            mimeType = "text/csv;charset=utf-8;";
        } else {
            content = `City of Cabuyao DRRMO\n\nReport: ${reportType}\nDate: ${dateFrom || "All Time"} to ${dateTo || "All Time"}\n\nGenerated by EvacTech System.`;
            filename = `${reportType.replace(/\s+/g, "_")}.pdf`;
            mimeType = "application/pdf";
        }

        const blob = new Blob([content], { type: mimeType });
        const link = document.createElement("a");
        const url = URL.createObjectURL(blob);

        link.setAttribute("href", url);
        link.setAttribute("download", filename);
        link.style.visibility = "hidden";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);

        setToastMessage(`Downloading report as ${format.toUpperCase()}...`);
    };

    const handlePrint = () => {
        setToastMessage(`Opening print dialog...`);
        setTimeout(() => {
            window.print();
        }, 500);
    };

    const renderPreviewContent = () => {
        if (reportType === "Relief Distribution Report") {
            return (
                <div className="space-y-2">
                    {[
                        { label: "Rice (50kg Sack)", value: "350 sacks" },
                        { label: "Canned Goods", value: "2,600 pieces" },
                        { label: "Bottled Water (1L)", value: "1,500 bottles" },
                        { label: "Sleeping Mats", value: "600 pieces" },
                    ].map((item, i) => (
                        <div
                            key={i}
                            className="flex justify-between text-sm py-1.5 border-b border-gray-50 dark:border-gray-700/50 transition-colors"
                        >
                            <span className="text-gray-700 dark:text-gray-300 transition-colors">
                                {item.label}
                            </span>
                            <span className="font-medium text-gray-800 dark:text-gray-100 transition-colors">
                                {item.value}
                            </span>
                        </div>
                    ))}
                    <div className="flex justify-between text-sm pt-2 font-bold transition-colors">
                        <span className="text-gray-800 dark:text-gray-100">
                            Total Items Distributed
                        </span>
                        <span className="text-teal-700 dark:text-teal-400">
                            5,050 items
                        </span>
                    </div>
                </div>
            );
        }

        if (reportType === "Shelter Occupancy Report") {
            return (
                <div className="space-y-2">
                    {[
                        {
                            label: "Mamatid Elementary",
                            value: "750 / 800 (Critical)",
                        },
                        {
                            label: "Cabuyao City Hall",
                            value: "342 / 500 (Active)",
                        },
                        {
                            label: "Marinig Covered Court",
                            value: "120 / 300 (Active)",
                        },
                        {
                            label: "Banay-Banay Brgy Hall",
                            value: "199 / 200 (Critical)",
                        },
                    ].map((item, i) => (
                        <div
                            key={i}
                            className="flex justify-between text-sm py-1.5 border-b border-gray-50 dark:border-gray-700/50 transition-colors"
                        >
                            <span className="text-gray-700 dark:text-gray-300 transition-colors">
                                {item.label}
                            </span>
                            <span
                                className={`font-medium transition-colors ${item.value.includes("Critical") ? "text-red-600 dark:text-red-400" : "text-gray-800 dark:text-gray-100"}`}
                            >
                                {item.value}
                            </span>
                        </div>
                    ))}
                    <div className="flex justify-between text-sm pt-2 font-bold transition-colors">
                        <span className="text-gray-800 dark:text-gray-100">
                            Total System Occupancy
                        </span>
                        <span className="text-teal-700 dark:text-teal-400">
                            1,411 Persons
                        </span>
                    </div>
                </div>
            );
        }

        if (reportType === "Vulnerable Groups Summary") {
            return (
                <div className="space-y-2">
                    {[
                        { label: "Children (Under 12)", value: "145 persons" },
                        { label: "Senior Citizens", value: "89 persons" },
                        { label: "Pregnant Women", value: "34 persons" },
                        {
                            label: "Persons with Disabilities",
                            value: "22 persons",
                        },
                    ].map((item, i) => (
                        <div
                            key={i}
                            className="flex justify-between text-sm py-1.5 border-b border-gray-50 dark:border-gray-700/50 transition-colors"
                        >
                            <span className="text-gray-700 dark:text-gray-300 transition-colors">
                                {item.label}
                            </span>
                            <span className="font-medium text-gray-800 dark:text-gray-100 transition-colors">
                                {item.value}
                            </span>
                        </div>
                    ))}
                    <div className="flex justify-between text-sm pt-2 font-bold transition-colors">
                        <span className="text-gray-800 dark:text-gray-100">
                            Total Vulnerable Individuals
                        </span>
                        <span className="text-teal-700 dark:text-teal-400">
                            290 persons
                        </span>
                    </div>
                </div>
            );
        }

        return (
            <div className="space-y-2">
                {[
                    "Barangay Mamatid",
                    "Barangay Sala",
                    "Barangay Marinig",
                    "Barangay Gulod",
                    "Barangay Banay-Banay",
                ].map((b, i) => (
                    <div
                        key={b}
                        className="flex justify-between text-sm py-1.5 border-b border-gray-50 dark:border-gray-700/50 transition-colors"
                    >
                        <span className="text-gray-700 dark:text-gray-300 transition-colors">
                            {b}
                        </span>
                        <span className="font-medium text-gray-800 dark:text-gray-100 transition-colors">
                            {[14, 11, 8, 9, 18][i]} families
                        </span>
                    </div>
                ))}
                <div className="flex justify-between text-sm pt-2 font-bold transition-colors">
                    <span className="text-gray-800 dark:text-gray-100">
                        Total
                    </span>
                    <span className="text-teal-700 dark:text-teal-400">
                        60 families
                    </span>
                </div>
            </div>
        );
    };

    return (
        <Layout
            currentPage="Generate Report"
            title="Generate Report"
            subtitle="Configure and preview custom system reports."
        >
            {toastMessage && (
                <Toast
                    message={toastMessage}
                    onClose={() => setToastMessage(null)}
                />
            )}

            <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                {/* Left — Configuration */}
                <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-6 transition-colors self-start">
                    <div className="flex items-center gap-2 mb-6">
                        <div className="p-2 rounded-lg bg-teal-50 dark:bg-teal-900/30 transition-colors">
                            <Filter
                                size={16}
                                className="text-teal-600 dark:text-teal-400"
                            />
                        </div>
                        <h3 className="font-semibold text-gray-800 dark:text-gray-100 transition-colors">
                            Report Configuration
                        </h3>
                    </div>

                    <div className="space-y-5">
                        {/* Report Type */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5 transition-colors">
                                Report Type
                            </label>
                            <select
                                value={reportType}
                                onChange={(e) => {
                                    setReportType(e.target.value);
                                    setGenerated(false);
                                }}
                                className="w-full px-3 py-3 border border-gray-200 dark:border-gray-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 transition-colors cursor-pointer"
                            >
                                {REPORT_TYPES.map((r) => (
                                    <option
                                        key={r}
                                        className="dark:bg-gray-800"
                                    >
                                        {r}
                                    </option>
                                ))}
                            </select>
                        </div>

                        {/* Date Range */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1.5 transition-colors">
                                Date Range
                            </label>
                            <div className="flex items-center gap-3">
                                <input
                                    type="date"
                                    value={dateFrom}
                                    onChange={(e) =>
                                        setDateFrom(e.target.value)
                                    }
                                    className="flex-1 px-3 py-3 border border-gray-200 dark:border-gray-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 dark:[color-scheme:dark] transition-colors"
                                />
                                <span className="text-gray-400 dark:text-gray-500 text-sm transition-colors">
                                    to
                                </span>
                                <input
                                    type="date"
                                    value={dateTo}
                                    onChange={(e) => setDateTo(e.target.value)}
                                    className="flex-1 px-3 py-3 border border-gray-200 dark:border-gray-700 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 dark:[color-scheme:dark] transition-colors"
                                />
                            </div>
                        </div>

                        {/* Format */}
                        <div>
                            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2 transition-colors">
                                Format
                            </label>
                            <div className="flex items-center gap-6">
                                <label className="flex items-center gap-2 cursor-pointer">
                                    <input
                                        type="radio"
                                        name="format"
                                        value="pdf"
                                        checked={format === "pdf"}
                                        onChange={() => setFormat("pdf")}
                                        className="accent-teal-600 dark:accent-teal-500"
                                    />
                                    <span className="text-sm text-gray-700 dark:text-gray-300 transition-colors">
                                        PDF
                                    </span>
                                </label>
                                <label className="flex items-center gap-2 cursor-pointer">
                                    <input
                                        type="radio"
                                        name="format"
                                        value="excel"
                                        checked={format === "excel"}
                                        onChange={() => setFormat("excel")}
                                        className="accent-teal-600 dark:accent-teal-500"
                                    />
                                    <span className="text-sm text-gray-700 dark:text-gray-300 transition-colors">
                                        Excel (CSV)
                                    </span>
                                </label>
                            </div>
                        </div>

                        {/* Generate Button */}
                        <button
                            onClick={handleGenerate}
                            className="w-full py-3 rounded-lg text-white font-semibold text-sm transition-all hover:opacity-90 active:scale-[0.98] mt-2 shadow-sm"
                            style={{
                                background:
                                    "linear-gradient(90deg, #0d9488, #0f766e)",
                            }}
                        >
                            Generate Report
                        </button>
                    </div>
                </div>

                {/* Right — Preview */}
                <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-100 dark:border-gray-700 p-6 transition-colors self-start min-h-[400px]">
                    <div className="flex items-center justify-between mb-6">
                        <div className="flex items-center gap-2">
                            <div className="p-2 rounded-lg bg-gray-50 dark:bg-gray-700 transition-colors">
                                <FileText
                                    size={16}
                                    className="text-gray-500 dark:text-gray-400"
                                />
                            </div>
                            <h3 className="font-semibold text-gray-800 dark:text-gray-100 transition-colors">
                                Report Preview
                            </h3>
                        </div>
                        {generated && (
                            <div className="flex items-center gap-2">
                                <button
                                    onClick={handlePrint}
                                    className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-500 dark:text-gray-400 transition-colors"
                                    title="Print Report"
                                >
                                    <Printer size={16} />
                                </button>
                                <button
                                    onClick={handleDownload}
                                    className="p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-500 dark:text-gray-400 transition-colors"
                                    title={`Download ${format.toUpperCase()}`}
                                >
                                    <Download size={16} />
                                </button>
                            </div>
                        )}
                    </div>

                    {!generated ? (
                        <div className="flex flex-col items-center justify-center h-64 text-center">
                            <div className="w-16 h-16 rounded-xl bg-gray-50 dark:bg-gray-900/50 flex items-center justify-center mb-4 transition-colors">
                                <FileText
                                    size={28}
                                    className="text-gray-300 dark:text-gray-600"
                                />
                            </div>
                            <p className="font-medium text-gray-500 dark:text-gray-400 text-sm transition-colors">
                                Ready to Generate
                            </p>
                            <p className="text-xs text-gray-400 dark:text-gray-500 mt-1 max-w-xs leading-relaxed transition-colors">
                                Select your configuration options on the left
                                and click "Generate Report" to view the preview
                                here.
                            </p>
                        </div>
                    ) : (
                        <div
                            id="printable-report"
                            className="border border-gray-100 dark:border-gray-700 rounded-lg p-4 transition-colors"
                        >
                            <div className="text-center border-b border-gray-100 dark:border-gray-700 pb-4 mb-4 transition-colors">
                                <p className="font-bold text-gray-800 dark:text-gray-100 text-base transition-colors">
                                    City of Cabuyao DRRMO
                                </p>
                                <p className="text-sm text-gray-600 dark:text-gray-400 mt-0.5 transition-colors">
                                    {reportType}
                                </p>
                                <p className="text-xs text-gray-400 dark:text-gray-500 mt-0.5 transition-colors">
                                    {dateFrom && dateTo
                                        ? `${dateFrom} to ${dateTo}`
                                        : "All Time Records"}
                                </p>
                            </div>
                            {renderPreviewContent()}
                        </div>
                    )}
                </div>
            </div>
        </Layout>
    );
}
